//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oraculum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OurResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OurResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oraculum.OurResources", typeof(OurResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllTablesSetTitle {
            get {
                return ResourceManager.GetString("AllTablesSetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Import Tables....
        /// </summary>
        public static string BulkImportTables {
            get {
                return ResourceManager.GetString("BulkImportTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to card.
        /// </summary>
        public static string CardInputHint {
            get {
                return ResourceManager.GetString("CardInputHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        public static string CardSequenceInputHint {
            get {
                return ResourceManager.GetString("CardSequenceInputHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubs.
        /// </summary>
        public static string CardSuitClubDisplay {
            get {
                return ResourceManager.GetString("CardSuitClubDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string CardSuitClubShort {
            get {
                return ResourceManager.GetString("CardSuitClubShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamonds.
        /// </summary>
        public static string CardSuitDiamondDisplay {
            get {
                return ResourceManager.GetString("CardSuitDiamondDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string CardSuitDiamondShort {
            get {
                return ResourceManager.GetString("CardSuitDiamondShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearts.
        /// </summary>
        public static string CardSuitHeartDisplay {
            get {
                return ResourceManager.GetString("CardSuitHeartDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string CardSuitHeartShort {
            get {
                return ResourceManager.GetString("CardSuitHeartShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spades.
        /// </summary>
        public static string CardSuitSpadeDisplay {
            get {
                return ResourceManager.GetString("CardSuitSpadeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string CardSuitSpadeShort {
            get {
                return ResourceManager.GetString("CardSuitSpadeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ace.
        /// </summary>
        public static string CardValueAceDisplay {
            get {
                return ResourceManager.GetString("CardValueAceDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string CardValueAceShort {
            get {
                return ResourceManager.GetString("CardValueAceShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Joker.
        /// </summary>
        public static string CardValueBlackJokerDisplay {
            get {
                return ResourceManager.GetString("CardValueBlackJokerDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BJ.
        /// </summary>
        public static string CardValueBlackJokerShort {
            get {
                return ResourceManager.GetString("CardValueBlackJokerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of Clubs.
        /// </summary>
        public static string CardValueClubDisplay {
            get {
                return ResourceManager.GetString("CardValueClubDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}C.
        /// </summary>
        public static string CardValueClubShort {
            get {
                return ResourceManager.GetString("CardValueClubShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of Diamonds.
        /// </summary>
        public static string CardValueDiamondDisplay {
            get {
                return ResourceManager.GetString("CardValueDiamondDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}D.
        /// </summary>
        public static string CardValueDiamondShort {
            get {
                return ResourceManager.GetString("CardValueDiamondShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of Hearts.
        /// </summary>
        public static string CardValueHeartDisplay {
            get {
                return ResourceManager.GetString("CardValueHeartDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}H.
        /// </summary>
        public static string CardValueHeartShort {
            get {
                return ResourceManager.GetString("CardValueHeartShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jack.
        /// </summary>
        public static string CardValueJackDisplay {
            get {
                return ResourceManager.GetString("CardValueJackDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J.
        /// </summary>
        public static string CardValueJackShort {
            get {
                return ResourceManager.GetString("CardValueJackShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King.
        /// </summary>
        public static string CardValueKingDisplay {
            get {
                return ResourceManager.GetString("CardValueKingDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        public static string CardValueKingShort {
            get {
                return ResourceManager.GetString("CardValueKingShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen.
        /// </summary>
        public static string CardValueQueenDisplay {
            get {
                return ResourceManager.GetString("CardValueQueenDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        public static string CardValueQueenShort {
            get {
                return ResourceManager.GetString("CardValueQueenShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Joker.
        /// </summary>
        public static string CardValueRedJokerDisplay {
            get {
                return ResourceManager.GetString("CardValueRedJokerDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RJ.
        /// </summary>
        public static string CardValueRedJokerShort {
            get {
                return ResourceManager.GetString("CardValueRedJokerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of Spades.
        /// </summary>
        public static string CardValueSpadeDisplay {
            get {
                return ResourceManager.GetString("CardValueSpadeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}S.
        /// </summary>
        public static string CardValueSpadeShort {
            get {
                return ResourceManager.GetString("CardValueSpadeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        public static string DiceSequenceInputHint {
            get {
                return ResourceManager.GetString("DiceSequenceInputHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}+{1}.
        /// </summary>
        public static string DiceSumInputHint {
            get {
                return ResourceManager.GetString("DiceSumInputHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be no more than {0}..
        /// </summary>
        public static string DieValueMaximumError {
            get {
                return ResourceManager.GetString("DieValueMaximumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be at least 1..
        /// </summary>
        public static string DieValueMinimumError {
            get {
                return ResourceManager.GetString("DieValueMinimumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditTableButtonLabel {
            get {
                return ResourceManager.GetString("EditTableButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Sets.
        /// </summary>
        public static string HideSetsButtonLabel {
            get {
                return ResourceManager.GetString("HideSetsButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Tables….
        /// </summary>
        public static string ImportTables {
            get {
                return ResourceManager.GetString("ImportTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Table.
        /// </summary>
        public static string NewTableTitle {
            get {
                return ResourceManager.GetString("NewTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        public static string RollButtonLabel {
            get {
                return ResourceManager.GetString("RollButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled {0}….
        /// </summary>
        public static string RollResultKey {
            get {
                return ResourceManager.GetString("RollResultKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling on {0}….
        /// </summary>
        public static string RollResultTable {
            get {
                return ResourceManager.GetString("RollResultTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        public static string RollTableButtonLabel {
            get {
                return ResourceManager.GetString("RollTableButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Sets.
        /// </summary>
        public static string ShowSetsButtonLabel {
            get {
                return ResourceManager.GetString("ShowSetsButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d{0}.
        /// </summary>
        public static string SingleDieInputHint {
            get {
                return ResourceManager.GetString("SingleDieInputHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;unknown&gt;.
        /// </summary>
        public static string UnknownTableName {
            get {
                return ResourceManager.GetString("UnknownTableName", resourceCulture);
            }
        }
    }
}
